server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml      # mybatis 配置文件所在路径
  type-aliases-package: indi.jsees.springcloud.entities  # 所有 Entity 别名所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                     # mybatis 映射文件

spring:
  application:
    name: microservicecloud-dept                          # 这个名字就是对外暴露的微服务名字非常重要
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource          # 当前数据源操作类型
    #driver-class-name: org.gjt.mm.mysql.Driver            # mysql 驱动包
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:8808/springcloud01?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC            # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                         # 数据库连接池的最小持续连接数
      initial-size: 5                                     # 初始化连接数
      max-total: 5                                        # 最大连接数
      max-wait-millis: 200                                # 等待连接获取的最大超时时间
      eureka:
        client:   # 客户端注册进eureka 服务列表内
          service-url:
            #单机 defaultZone: http://localhost:7001/eureka
            defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
        instance:
          instance-id: microservicecloud-dept8001  # 自定义服务名称信息
          prefer-ip-address: true       # 访问路径可以显示 IP 地址

      info:
        app.name: jsees-microservicecloud
        company.name: www.baidu.com
        build.artifactId: $project.artifactId$
        build.version: $project.version$